name: CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * 2"
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/rubocop --color --format github
